### ISSUE TITLE
panic when return type has NaiveDate

### ISSUE THREAD

**Issue by Matrix-Zhang** [graphql-rust/juniper#155]
```
thread '<unnamed>' panicked at 'a Display implementation return an error unexpectedly: Error', /checkout/src/libcore/result.rs:916:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:809
  11: <T as alloc::string::ToString>::to_string
             at /checkout/src/liballoc/string.rs:2053
  12: juniper::integrations::chrono::<impl juniper::types::base::GraphQLType for chrono::naive::date::NaiveDate>::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/integrations/chrono.rs:59
  13: <juniper::executor::Executor<'a, CtxT>>::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:287
  14: <juniper::executor::Executor<'a, CtxT>>::resolve_with_ctx
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:277
  15: <gas_rs::model::public::order::team::TeamOrder as juniper::types::base::GraphQLType>::resolve_field
             at src/model/public/order/team.rs:7
  16: juniper::types::base::resolve_selection_set_into
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/types/base.rs:382
  17: juniper::types::base::GraphQLType::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/types/base.rs:314
  18: juniper::types::pointers::<impl juniper::types::base::GraphQLType for &'a T>::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/types/pointers.rs:115
  19: <juniper::executor::Executor<'a, CtxT>>::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:287
  20: <juniper::executor::Executor<'a, CtxT>>::resolve_into_value
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:298
  21: juniper::types::containers::resolve_into_list
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/types/containers.rs:169
  22: juniper::types::containers::<impl juniper::types::base::GraphQLType for alloc::vec::Vec<T>>::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/types/containers.rs:84
  23: <juniper::executor::Executor<'a, CtxT>>::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:287
  24: <juniper::executor::Executor<'a, CtxT>>::resolve_into_value
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:298
  25: juniper::types::containers::<impl juniper::types::base::GraphQLType for core::option::Option<T>>::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/types/containers.rs:30
  26: <juniper::executor::Executor<'a, CtxT>>::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:287
  27: <juniper::executor::Executor<'a, CtxT>>::resolve_with_ctx
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:277
  28: <gas_rs::graphql::schema::QueryRoot as juniper::types::base::GraphQLType>::resolve_field::{{closure}}
             at src/graphql/schema/mod.rs:26
  29: <core::result::Result<T, E>>::and_then
             at /checkout/src/libcore/result.rs:621
  30: <gas_rs::graphql::schema::QueryRoot as juniper::types::base::GraphQLType>::resolve_field
             at ./<graphql_object macros>:93
  31: juniper::schema::schema::<impl juniper::types::base::GraphQLType for juniper::schema::model::RootNode<'a, QueryT, MutationT>>::resolve_field
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/schema/schema.rs:41
  32: juniper::types::base::resolve_selection_set_into
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/types/base.rs:382
  33: juniper::types::base::GraphQLType::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/types/base.rs:314
  34: juniper::types::pointers::<impl juniper::types::base::GraphQLType for &'a T>::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/types/pointers.rs:115
  35: <juniper::executor::Executor<'a, CtxT>>::resolve
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:287
  36: <juniper::executor::Executor<'a, CtxT>>::resolve_into_value
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:298
  37: juniper::executor::execute_validated_query
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/executor/mod.rs:558
  38: juniper::execute
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/lib.rs:207
  39: juniper::http::GraphQLRequest::execute
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper/src/http/mod.rs:70
  40: <juniper_iron::GraphQLHandler<'a, CtxFactory, Query, Mutation, CtxT>>::execute
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper_iron/src/lib.rs:229
  41: <juniper_iron::GraphQLHandler<'a, CtxFactory, Query, Mutation, CtxT> as iron::middleware::Handler>::handle
             at /home/matrix/.cargo/git/checkouts/juniper-aa5e857cd28538c7/63d8a3d/juniper_iron/src/lib.rs:271
  42: <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/iron-0.6.0/src/middleware/mod.rs:395
  43: <mount::mount::Mount as iron::middleware::Handler>::handle
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/mount-0.4.0/src/mount.rs:122
  44: <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/iron-0.6.0/src/middleware/mod.rs:395
  45: <gas_rs::custom::middleware::logger::Logger as iron::middleware::AroundMiddleware>::around::{{closure}}
             at src/custom/middleware/logger.rs:16
  46: <F as iron::middleware::Handler>::handle
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/iron-0.6.0/src/middleware/mod.rs:389
  47: <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/iron-0.6.0/src/middleware/mod.rs:395
  48: <iron_sessionstorage::SessionStorage<B> as iron::middleware::AroundMiddleware>::around::{{closure}}
             at /home/matrix/.cargo/git/checkouts/iron-sessionstorage-578848c1c042ea6d/2c79d93/src/lib.rs:111
  49: <F as iron::middleware::Handler>::handle
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/iron-0.6.0/src/middleware/mod.rs:389
  50: <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/iron-0.6.0/src/middleware/mod.rs:395
  51: iron::middleware::Chain::continue_from_handler
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/iron-0.6.0/src/middleware/mod.rs:359
  52: iron::middleware::Chain::continue_from_before
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/iron-0.6.0/src/middleware/mod.rs:353
  53: <iron::middleware::Chain as iron::middleware::Handler>::handle
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/iron-0.6.0/src/middleware/mod.rs:277
  54: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/iron-0.6.0/src/iron.rs:176
  55: <hyper::server::Worker<H>>::keep_alive_loop
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-0.10.13/src/server/mod.rs:337
  56: <hyper::server::Worker<H>>::handle_connection
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-0.10.13/src/server/mod.rs:283
  57: hyper::server::handle::{{closure}}
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-0.10.13/src/server/mod.rs:242
  58: hyper::server::listener::spawn_with::{{closure}}
             at /home/matrix/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/hyper-0.10.13/src/server/listener.rs:50
```

**Comment by sporto** [comment]
I'm seeing the same

**Comment by LegNeato** [comment]
Can you try the PR for https://github.com/graphql-rust/juniper/issues/150 and see if that fixes it?

**Comment by sporto** [comment]
https://github.com/graphql-rust/juniper/pull/151 should fix this. 
Note that this PR changes the serialisation of `NaiveDate`.

**Comment by LegNeato** [comment]
Closing this as it is assumed fixed. Please re-open if the original issue was not completely resolved.
